name: Main workflow # name of workflow

on: [ push, pull_request ]  # when it should be done (work)

jobs:
  main:
    runs-on: macos-11  # to run in which environment, also we can do our own environment

    steps:
      # Need this for any work with repository.
      - name: Checkout # to work with repository
        uses: actions/checkout@v3 # for environment preparation for spesific python in our case 3.10
      - name: Set up Python # for environment preparation for spesific python in our case 3.10
        uses: actions/setup-python@v4 # for environment preparation for spesific python in our case 3.10
        with:
          python-version: "3.10" # for environment preparation for spesific python in our case 3.10
      - name: Install dependencies # below different commands
        run: |
          python -m pip install --upgrade pip
          pip install --requirement requirements.txt
      - name: Make autoformatting # new command with black check
        run: |
          black ./
      - name: Check codestyle # new command with flake8 check
        run: |
          flake8 ./